[supervisord]
nodaemon=true
logfile=/tmp/supervisord.log

[program:backend]
command=sh -c "uvicorn app.main:app --host 0.0.0.0 --port 8000"
directory=/app
autostart=true
autorestart=true
stdout_logfile=/tmp/backend.log
stderr_logfile=/tmp/backend.log

[program:nginx]
command=nginx -g "daemon off;"
autostart=true
autorestart=true
stdout_logfile=/tmp/nginx.log
stderr_logfile=/tmp/nginx.log
