from enum import Enum

class Intent(str, Enum):
    GREETING = "GREETING"
    GET_ATTENDANCE = "GET_ATTENDANCE"
    GET_ATTENDANCE_HISTORY = "GET_ATTENDANCE_HISTORY"
    APPLY_LEAVE = "APPLY_LEAVE"
    GET_LEAVE_STATUS = "GET_LEAVE_STATUS"
    CANCEL_LEAVE = "CANCEL_LEAVE"
    CREATE_OUTING = "CREATE_OUTING"
    GET_OUTING_STATUS = "GET_OUTING_STATUS"
    CANCEL_OUTING = "CANCEL_OUTING"
    CREATE_COMPLAINT = "CREATE_COMPLAINT"
    GET_COMPLAINTS = "GET_COMPLAINTS"
    GET_COMPLAINT_STATUS = "GET_COMPLAINT_STATUS"
    GET_PROFILE = "GET_PROFILE"
    GET_ROOM = "GET_ROOM"
    UNKNOWN = "UNKNOWN"
